// ============================================================================
// POSTER STYLE CONFIGURATION
// ============================================================================

window.PosterConfig = {
    // Default values applied when switching poster style
    styles: {
        classic: {
            borderColor: "#000000",
            textColor: "#000000",
            bgColor: "#ffffff",
            cityFont: "Montserrat, sans-serif",
            countryFont: "Montserrat, sans-serif",
            coordsFont: "Inter, sans-serif",
            showBuildings: false,
            buildingColor: "#dcdcdc",
            fadeIntensity: 50,
        },
        blueprint: {
            borderColor: "#294380",
            textColor: "#294380",
            bgColor: "#ffffff",
            cityFont: "Space Mono, monospace",
            countryFont: "Space Mono, monospace",
            coordsFont: "Space Mono, monospace",
            showBuildings: false,
            buildingColor: "#e6eaf0",
            fadeIntensity: 50,
        },
        vintage: {
            borderColor: "#8b7355",
            textColor: "#5c4a3a",
            bgColor: "#e0d8c8",
            cityFont: "Montserrat, sans-serif",
            countryFont: "Montserrat, sans-serif",
            coordsFont: "Inter, sans-serif",
            showBuildings: false,
            buildingColor: "#d4c5b0",
            fadeIntensity: 50,
        },
        midnight: {
            borderColor: "#00f3ff",
            textColor: "#00f3ff",
            bgColor: "#0a0a0f",
            cityFont: "Space Mono, monospace",
            countryFont: "Space Mono, monospace",
            coordsFont: "Space Mono, monospace",
            showBuildings: true,
            buildingColor: "#fdf6e3",
            fadeIntensity: 50,
        },
        swiss: {
            borderColor: "#000000",
            textColor: "#000000",
            bgColor: "#ffffff",
            cityFont: "Inter, sans-serif",
            countryFont: "Inter, sans-serif",
            coordsFont: "Inter, sans-serif",
            showBuildings: false,
            buildingColor: "#dcdcdc",
            fadeIntensity: 50,
        },
        botanical: {
            borderColor: "#3a5a40",
            textColor: "#3a5a40",
            bgColor: "#f1f3f0",
            cityFont: "Playfair Display, serif",
            countryFont: "Lora, serif",
            coordsFont: "Raleway, sans-serif",
            showBuildings: false,
            buildingColor: "#ddbea9",
            fadeIntensity: 50,
        },
        modern: {
            borderColor: "#2c2c2c",
            textColor: "#2c2c2c",
            bgColor: "#ffffff",
            cityFont: "Inter, sans-serif",
            countryFont: "Inter, sans-serif",
            coordsFont: "Inter, sans-serif",
            showBuildings: false,
            buildingColor: "#e8e8e8",
            fadeIntensity: 40,
        },
        ocean: {
            borderColor: "#4da6c9",
            textColor: "#a8d8ea",
            bgColor: "#1b2838",
            cityFont: "Raleway, sans-serif",
            countryFont: "Raleway, sans-serif",
            coordsFont: "Inter, sans-serif",
            showBuildings: false,
            buildingColor: "#1e3448",
            fadeIntensity: 60,
        },
        asphalt: {
            borderColor: "#e0e0e0",
            textColor: "#e0e0e0",
            bgColor: "#2d2d2d",
            cityFont: "Oswald, sans-serif",
            countryFont: "Oswald, sans-serif",
            coordsFont: "Space Mono, monospace",
            showBuildings: true,
            buildingColor: "#3a3a3a",
            fadeIntensity: 50,
        },
        neon: {
            borderColor: "#ff00ff",
            textColor: "#ff00ff",
            bgColor: "#1a0030",
            cityFont: "Space Mono, monospace",
            countryFont: "Space Mono, monospace",
            coordsFont: "Space Mono, monospace",
            showBuildings: true,
            buildingColor: "#220044",
            fadeIntensity: 50,
        },
    },

    // Font options for the UI
    fontOptions: [
        { name: "Inter", value: "Inter, sans-serif" },
        { name: "Montserrat", value: "Montserrat, sans-serif" },
        { name: "Space Mono", value: "Space Mono, monospace" },
        { name: "Playfair Display", value: "Playfair Display, serif" },
        { name: "Lora", value: "Lora, serif" },
        { name: "Oswald", value: "Oswald, sans-serif" },
        { name: "Raleway", value: "Raleway, sans-serif" },
    ],

    // Border style options for the UI
    borderOptions: [
        { name: "Classic (Simple)", value: "classic" },
        { name: "Vintage (Double)", value: "vintage" },
        { name: "Blueprint (Technical)", value: "blueprint" },
        { name: "Midnight (Neon)", value: "midnight" },
        { name: "Swiss (Bold)", value: "swiss" },
        { name: "Botanical (Frame)", value: "botanical" },
        { name: "Modern (Clean)", value: "modern" },
        { name: "Ocean (Deep)", value: "ocean" },
        { name: "Asphalt (Urban)", value: "asphalt" },
        { name: "Neon (Glow)", value: "neon" },
    ],

    // Map shape options
    mapShapeOptions: [
        { name: "None", value: "none" },
        { name: "Circle", value: "circle" },
        { name: "Heart", value: "heart" },
        { name: "Star", value: "star" },
    ],

    // Label placement options
    labelPlacementOptions: [
        { name: "Bottom", value: "bottom" },
        { name: "Top", value: "top" },
        { name: "Center", value: "center" },
        { name: "Split", value: "split" },
    ],
};
